### ISSUE TITLE
Make it clear in the docs why surfaceId-screenId pattern should be used

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [liferay/sennajs.com#26]
According to https://github.com/eduardolundgren/senna/pull/53, an `id` attribute in the format of `*-default` should exist inside the parent surface element. That's because:

> Surfaces can contain static content that can co-exist with the surface navigation, that's why Senna requires to the user specifies a default surface with the surfaceId-screenId, in this case the default screen is default, therefore surfaceId-default contract.

This should be explicitly declared in the docs page somewhere, in order to clarify the reasoning of why the `*-default` elements exists in the examples and avoid any kind of potencial confusion for newcomers.

The content of the issue mentioned above is pretty buried in the closed issues of the main repository, but represents a very useful piece of information that should be documented.

**Comment by zenorocha** [comment]
> Closing issue since default surfaces no longer exists.
