### ISSUE TITLE
Explain error handling

### ISSUE THREAD

**Issue by zenorocha** [liferay/sennajs.com#34]
When using a SPA solution, it's important to detect navigation errors. We should explain more how to handle errors with examples like this:

```js
senna.dataAttributeHandler.getApp().on('endNavigate', function(event) {
 if (event.error.requestError) {
   alert('Some error happened trying to load the page.');
 }
})
```

**Comment by mjbradford89** [comment]
Closing this as error handling has been added to the docs in https://github.com/liferay/sennajs.com/pull/35
