### ISSUE TITLE
Add "Who uses Senna" section on the website

### ISSUE THREAD

**Issue by eduardolundgren** [liferay/sennajs.com#36]
I just noticed that users of Senna are growing:

* Liferay

And more. That would be cool to add their logos to the website. What do you guys think?

**Comment by zenorocha** [comment]
Are you sure whodidthis is using Senna? I couldn't find it on their source code

**Comment by eduardolundgren** [comment]
I got tricked by the autocomplete of Developer Tools, through senna was loaded in this whodidthis. Nevermind.
