### ISSUE TITLE
Perform a Js task at every route change

### ISSUE THREAD

**Issue by caneta** [liferay/sennajs.com#47]
In Liferay 7 I would like to perform a JavaScript routine every time I click on a Navigation link or if I change language.
Now I see that the page is not reloaded anymore like in Liferay 6.2 and so I was wondering how to trigger the event of a page change in a SPA powered by senna.
How can I achieve this?
Thank you

**Comment by brunobasto** [comment]
Hello, @caneta 

You can try listening for the senna lifecycle events exposed in Liferay DXP. An example could be:

`Liferay.SPA.app.on('endNavigate', function() { ...execute routine... });`

**Comment by jbalsas** [comment]
Hey @caneta, on  top of what @brunobasto said, we also have a more specific mechanism meant to **persist and restore** some state from navigations. 

We're using it for example to keep the selection and the `management_bar` state if you navigate through the pages in a `search_container`.

This is a very specific (and not-yet-documented) framework, but you can see it working in [management_bar.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-taglib/frontend-taglib/src/main/resources/META-INF/resources/management_bar/js/management_bar.js#L135-L147) and in [search_container_select.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/search_container_select.js#L142-L153) 

If you think this is what you're looking for, we can get into more detail, but in any case, Bruno's solution is the more generic way to do that.

**Comment by caneta** [comment]
Hi @jbalsas, that's exactly what I need because I have to move DOM elements through JavaScript, before the page is loaded, so more details would be really appreciated.

And another issue I'm facing right now is the persistence of AMD module loaded when I move from a page to another, if the load is inside a `<script>` tag in the html.

I guess they could be related problems...

**Comment by jbalsas** [comment]
Hey @caneta, not sure about the second issue... in any case I think both of these conversations belong in the Liferay Forums since they're both about integration and not the framework itself... 

Would you be so kind as to open a couple of threads in there so we can document the answers and share the knowledge in case someone else is having the same doubts? I'll make sure to followup there and provide any additional information you may need.

Thanks!

**Comment by caneta** [comment]
You are right @jbalsas: [here's the first one](https://web.liferay.com/it/community/forums/-/message_boards/message/82179598).
I will experiment a little bit more before posting for the second one.

**Comment by zenorocha** [comment]
Thanks guys!

**Comment by jbalsas** [comment]
For future reference, here's the [answer](https://web.liferay.com/es/community/forums/-/message_boards/view_message/82206012#_19_message_82206012)

**Comment by caneta** [comment]
[Here's the thread](https://web.liferay.com/community/forums/-/message_boards/message/82256366) about my second issue with AMD modules that I barely outlined above.
